form_armor:
    resource: "@FormArmorBundle/Resources/config/routing.yml"
    prefix:   /formarmor

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /compte

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group